#!/bin/bash

echo $1 #path

echo "Creating recipe"

echo ''>default_url.rb
echo ''>/home/esamp/chef-repo/cookbooks/default_url/recipes/default.rb

cat template_1.rb>default_url.rb

grep -rl url default_1.rb | xargs sed -i "s#url#$1#g"

echo "Creating cookbook"

#cd /home/esamp/chef-repo/

knife cookbook create default_url

cd /home/esamp/chef-repo/cookbooks/default_url/recipes

cat /home/esamp/chef-repo/default_url.rb>>default.rb

echo "Uploading cookbook"

knife cookbook upload default_1

echo "Success!"
