name             'vlc'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures vlc'
long_description 'Installs/Configures vlc'
version          '0.1.0'
